[build-system]
requires = [
    "scikit-build-core",
    "pxr-tf-dev==25.5.1.*",
    "pxr-trace-dev==25.5.1.*",
    "pxr-boost-dev==25.5.1.*",
    "pxr-tbb-dev==2022.1.0.*"
]
build-backend = "scikit_build_core.build"

[project]
name = "pxr-work-dev"
version = "25.5.1"
description = "C++ headers and CMake config for developing with pxr-work"
readme = "README.md"
requires-python = ">=3.8"
license-files = ["LICENSE.txt", "NOTICE.txt"]
keywords = ["pixar", "open-usd", "dev"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows :: Windows 10",
]
dependencies = [
    "pxr-tf-dev==25.5.1.*",
    "pxr-trace-dev==25.5.1.*",
    "pxr-boost-dev==25.5.1.*",
    "pxr-tbb-dev==2022.1.0.*"
]

[project.urls]
Repository = "https://github.com/untwine/pxr-work"

[tool.scikit-build]
cmake.version = ">=3.21,<4"
cmake.args = [
    "-DBUILD_TESTS=OFF",
    "-DBUILD_SHARED_LIBS=ON",
    "-DBUILD_PYTHON_BINDINGS=ON",
    "-DCMAKE_INSTALL_LIBDIR=pxr-work/lib",
    "-DCMAKE_INSTALL_INCLUDEDIR=pxr-work/include",
    "-DCMAKE_INSTALL_DATAROOTDIR=pxr-work",
    "-DCMAKE_INSTALL_PYTHON_LIBDIR=pxr-work/lib/python",

    # Aligned operator delete (used by TBB) requires macOS 10.13+
    "-DCMAKE_OSX_DEPLOYMENT_TARGET=10.13"
]
sdist.exclude = ["test", ".github"]
