name: test-macos

on:
  push:
    branches: [ dev, main ]

  workflow_dispatch:

permissions:
  contents: read

env:
  CTEST_OUTPUT_ON_FAILURE: True
  CONAN_REMOTE_NAME: untwine
  CONAN_REMOTE_URL: https://packages.untwine-openusd.dev/repository/conan/

jobs:
  test-macos:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [ macos-intel, macos-arm ]
        include:
          - os: macos-intel
            runs-on: macos-15-intel
          - os: macos-arm
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: 3.12

      - name: Install Ninja
        run: brew install ninja

      - name: Set up Conan
        shell: bash
        run: |
          pip install conan
          conan profile detect
          conan remote add "$CONAN_REMOTE_NAME" "$CONAN_REMOTE_URL" --force

      - name: Build
        shell: bash
        run: >
          conan build .
          -o build_tests=True
          -o python_version=3.12
          --options=*:shared=True
          -c tools.cmake.cmaketoolchain:generator=Ninja
          --build=missing

      - name: Test
        run: ctest --preset conan-release -VV --timeout 3600
