name: test-macos

on:
  push:
    branches: [ dev, main ]

  # Run tests once a week on Sunday.
  schedule:
    - cron: "0 6 * * 0"

permissions:
  contents: read

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja
  CTEST_OUTPUT_ON_FAILURE: True

jobs:
  test-macos:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        os: [ macOS-intel, macOS-arm ]
        include:
          - os: macos-intel
            runs-on: macos-13
          - os: macos-arm
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Create Build Environment
        run: |
          brew install ninja
          cmake -E make_directory ${{github.workspace}}/build
          python -m pip install pytest-cmake

      - name: Install Building Dependencies
        uses: ./.github/actions/building-deps
        with:
          oneTBB: 2021.12.0
          path: ${HOME}/.local

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake .. -D "CMAKE_PREFIX_PATH=${HOME}/.local"

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -VV -C Release
